// SPDX-License-Identifier: MIT OR Apache-2.0
// Copyright (C) 2026 Matthew Jackson

//! `Ed25519Verifier::verify`, RFC 8037 section 3.1 (EdDSA) reached with attacker-controlled key,
//! signature and signing input.
//!
//! This is the EdDSA half of the crypto-agility work that 0.10.0 added. The `JwsVerifier` contract
//! (see the VERIFICATION banner in `crate::jwt`) is absolute: the key is the caller's, the
//! algorithm was already chosen, and EVERY failure — a non-OKP `Jwk`, an OKP curve other than
//! Ed25519, an `x` that is not 32 base64url bytes, a signature that is not exactly 64 bytes
//! (INCLUDING the empty one — the third JWS segment is bytes of any length), and a signature that
//! simply does not verify — must be a `false`, never a panic and never a `true`. The backend uses
//! `verify_strict` (ZIP215 hardening) exactly so that small-order keys and non-canonical points
//! are also a `false`; this target feeds the lengths (0, 31, 32, 63, 64, 65) and shapes that would
//! break a naive slicing implementation.
//!
//! # Why this one is structure aware
//!
//! `Jwk`'s variant fields are public, so the generator builds the key DIRECTLY rather than through
//! `Jwk::from_json`. That lets the fuzzer hand the verifier keys `from_json` would have rejected (a
//! wrong-width `x`, a non-base64url `x`, an EC or RSA key in an EdDSA verifier's hand), which is
//! the defence-in-depth the verifier promises to hold on its own.
//!
//! # The invariants
//!
//! 1. NEVER PANICS, for any key/signature/input triple, and specifically for signatures and
//!    coordinates of 0, 31, 32, 63, 64 and 65 bytes.
//! 2. FALSE ON GARBAGE. A fuzzer cannot produce a valid Ed25519 signature, so `verify` MUST return
//!    `false` for every input this target generates. A `true` is a forgery this target caught.
//! 3. THE KIND GUARD HOLDS. An EC or RSA key, or an OKP key on a non-Ed25519 curve, handed to the
//!    EdDSA verifier returns `false` (fed explicitly so the path is exercised).

#![no_main]

use arbitrary::{Arbitrary, Unstructured};
use base64::engine::general_purpose::URL_SAFE_NO_PAD;
use base64::Engine as _;
use libfuzzer_sys::fuzz_target;
use oauth_as::jwt::{EcCurve, Jwk, OkpCurve};
use oauth_as::{Ed25519Verifier, JwsVerifier};

/// A base64url string encoding a buffer whose length straddles the 32-byte Ed25519 key width,
/// sometimes not base64url at all.
fn coord(u: &mut Unstructured<'_>) -> arbitrary::Result<String> {
    Ok(match u.int_in_range(0..=3)? {
        0 => URL_SAFE_NO_PAD.encode(u.bytes(32)?),
        1 => {
            let len = *u.choose(&[0usize, 31, 32, 33, 63, 64])?;
            URL_SAFE_NO_PAD.encode(u.bytes(len)?)
        }
        2 => String::arbitrary(u)?,
        // A base64url all-zeros key: the small-order point `verify_strict` must refuse.
        _ => URL_SAFE_NO_PAD.encode([0u8; 32]),
    })
}

/// The key handed to the verifier: mostly OKP (well-formed-ish and malformed), sometimes a non-OKP
/// key or a non-Ed25519 OKP curve so the kind guard is exercised.
fn arbitrary_key(u: &mut Unstructured<'_>) -> arbitrary::Result<Jwk> {
    Ok(match u.int_in_range(0..=3)? {
        0 | 1 => Jwk::Okp {
            crv: OkpCurve::Ed25519,
            x: coord(u)?,
            kid: None,
        },
        2 => Jwk::Ec {
            crv: EcCurve::P256,
            x: coord(u)?,
            y: coord(u)?,
            kid: None,
        },
        _ => Jwk::Rsa {
            n: coord(u)?,
            e: "AQAB".into(),
            kid: None,
        },
    })
}

#[derive(Debug)]
struct Input {
    key: Jwk,
    signing_input: Vec<u8>,
    signature: Vec<u8>,
}

impl<'a> Arbitrary<'a> for Input {
    fn arbitrary(u: &mut Unstructured<'a>) -> arbitrary::Result<Self> {
        let key = arbitrary_key(u)?;
        let signing_input = <Vec<u8>>::arbitrary(u)?;
        // The signature length straddles the fixed 64-byte width: 0, 31, 32, 63, 64, 65, plus the
        // fully arbitrary case.
        let signature = if u.arbitrary()? {
            let len = *u.choose(&[0usize, 31, 32, 63, 64, 65, 128])?;
            u.bytes(len)?.to_vec()
        } else {
            <Vec<u8>>::arbitrary(u)?
        };
        Ok(Input {
            key,
            signing_input,
            signature,
        })
    }
}

fuzz_target!(|input: Input| {
    let Input {
        key,
        signing_input,
        signature,
    } = input;

    // 1 and 2: the call must return (never panic) and must return false (no forgery).
    let verified = Ed25519Verifier.verify(&key, &signing_input, &signature);
    assert!(
        !verified,
        "Ed25519Verifier::verify returned true on fuzzer-generated bytes: \
         key {key:?}, input {signing_input:?}, sig {signature:?}"
    );
});
